//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20._08._2023entitydbfirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class vergiyonetimEntities : DbContext
    {
        public vergiyonetimEntities()
            : base("name=vergiyonetimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bakanlık> Bakanlık { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vatanda> Vatandas { get; set; }
        public virtual DbSet<Vergiler> Vergilers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int vatadd(string tc, string meslek, string adres, string telefon, string mail)
        {
            var tcParameter = tc != null ?
                new ObjectParameter("Tc", tc) :
                new ObjectParameter("Tc", typeof(string));
    
            var meslekParameter = meslek != null ?
                new ObjectParameter("Meslek", meslek) :
                new ObjectParameter("Meslek", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("vatadd", tcParameter, meslekParameter, adresParameter, telefonParameter, mailParameter);
        }
    
        public virtual int vatdel(Nullable<int> kisiNo)
        {
            var kisiNoParameter = kisiNo.HasValue ?
                new ObjectParameter("KisiNo", kisiNo) :
                new ObjectParameter("KisiNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("vatdel", kisiNoParameter);
        }
    
        public virtual ObjectResult<vatlist_Result> vatlist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vatlist_Result>("vatlist");
        }
    
        public virtual int vatupdate(Nullable<int> kisino, string tc, string meslek, string adres, string telefon, string mail)
        {
            var kisinoParameter = kisino.HasValue ?
                new ObjectParameter("Kisino", kisino) :
                new ObjectParameter("Kisino", typeof(int));
    
            var tcParameter = tc != null ?
                new ObjectParameter("Tc", tc) :
                new ObjectParameter("Tc", typeof(string));
    
            var meslekParameter = meslek != null ?
                new ObjectParameter("Meslek", meslek) :
                new ObjectParameter("Meslek", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("vatupdate", kisinoParameter, tcParameter, meslekParameter, adresParameter, telefonParameter, mailParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<telo_Result> telo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<telo_Result>("telo");
        }
    
        public virtual ObjectResult<berke_Result> berke()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<berke_Result>("berke");
        }
    
        public virtual int bakadd(string bakanlikAdi, string bakanlıkBaskan, Nullable<decimal> ciro, string merkez)
        {
            var bakanlikAdiParameter = bakanlikAdi != null ?
                new ObjectParameter("BakanlikAdi", bakanlikAdi) :
                new ObjectParameter("BakanlikAdi", typeof(string));
    
            var bakanlıkBaskanParameter = bakanlıkBaskan != null ?
                new ObjectParameter("BakanlıkBaskan", bakanlıkBaskan) :
                new ObjectParameter("BakanlıkBaskan", typeof(string));
    
            var ciroParameter = ciro.HasValue ?
                new ObjectParameter("Ciro", ciro) :
                new ObjectParameter("Ciro", typeof(decimal));
    
            var merkezParameter = merkez != null ?
                new ObjectParameter("Merkez", merkez) :
                new ObjectParameter("Merkez", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bakadd", bakanlikAdiParameter, bakanlıkBaskanParameter, ciroParameter, merkezParameter);
        }
    
        public virtual int bakdel(Nullable<int> bakanlikId)
        {
            var bakanlikIdParameter = bakanlikId.HasValue ?
                new ObjectParameter("BakanlikId", bakanlikId) :
                new ObjectParameter("BakanlikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bakdel", bakanlikIdParameter);
        }
    
        public virtual ObjectResult<baklist_Result> baklist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<baklist_Result>("baklist");
        }
    
        public virtual int bakupdate(Nullable<int> bakanlikId, string bakanlikAdi, string bakanlıkBaskan, Nullable<decimal> ciro, string merkez)
        {
            var bakanlikIdParameter = bakanlikId.HasValue ?
                new ObjectParameter("BakanlikId", bakanlikId) :
                new ObjectParameter("BakanlikId", typeof(int));
    
            var bakanlikAdiParameter = bakanlikAdi != null ?
                new ObjectParameter("BakanlikAdi", bakanlikAdi) :
                new ObjectParameter("BakanlikAdi", typeof(string));
    
            var bakanlıkBaskanParameter = bakanlıkBaskan != null ?
                new ObjectParameter("BakanlıkBaskan", bakanlıkBaskan) :
                new ObjectParameter("BakanlıkBaskan", typeof(string));
    
            var ciroParameter = ciro.HasValue ?
                new ObjectParameter("Ciro", ciro) :
                new ObjectParameter("Ciro", typeof(decimal));
    
            var merkezParameter = merkez != null ?
                new ObjectParameter("Merkez", merkez) :
                new ObjectParameter("Merkez", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bakupdate", bakanlikIdParameter, bakanlikAdiParameter, bakanlıkBaskanParameter, ciroParameter, merkezParameter);
        }
    
        public virtual ObjectResult<gruplama_Result> gruplama()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gruplama_Result>("gruplama");
        }
    
        public virtual ObjectResult<innervatandas_Result> innervatandas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<innervatandas_Result>("innervatandas");
        }
    
        public virtual ObjectResult<MerkezeGoreSıra_Result> MerkezeGoreSıra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MerkezeGoreSıra_Result>("MerkezeGoreSıra");
        }
    
        public virtual int sp_alterdiagram1(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram1", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram1(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram1", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram1(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram1", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition1_Result> sp_helpdiagramdefinition1(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition1_Result>("sp_helpdiagramdefinition1", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams1_Result> sp_helpdiagrams1(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams1_Result>("sp_helpdiagrams1", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram1(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram1", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams1");
        }
    
        public virtual int veradd(string vergiAdi, string vergiTipi, Nullable<decimal> tutar, Nullable<decimal> faiz, Nullable<int> kisiNo, Nullable<int> bakanlikId)
        {
            var vergiAdiParameter = vergiAdi != null ?
                new ObjectParameter("VergiAdi", vergiAdi) :
                new ObjectParameter("VergiAdi", typeof(string));
    
            var vergiTipiParameter = vergiTipi != null ?
                new ObjectParameter("VergiTipi", vergiTipi) :
                new ObjectParameter("VergiTipi", typeof(string));
    
            var tutarParameter = tutar.HasValue ?
                new ObjectParameter("Tutar", tutar) :
                new ObjectParameter("Tutar", typeof(decimal));
    
            var faizParameter = faiz.HasValue ?
                new ObjectParameter("Faiz", faiz) :
                new ObjectParameter("Faiz", typeof(decimal));
    
            var kisiNoParameter = kisiNo.HasValue ?
                new ObjectParameter("KisiNo", kisiNo) :
                new ObjectParameter("KisiNo", typeof(int));
    
            var bakanlikIdParameter = bakanlikId.HasValue ?
                new ObjectParameter("BakanlikId", bakanlikId) :
                new ObjectParameter("BakanlikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("veradd", vergiAdiParameter, vergiTipiParameter, tutarParameter, faizParameter, kisiNoParameter, bakanlikIdParameter);
        }
    
        public virtual int verdel(Nullable<int> vergiId)
        {
            var vergiIdParameter = vergiId.HasValue ?
                new ObjectParameter("VergiId", vergiId) :
                new ObjectParameter("VergiId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("verdel", vergiIdParameter);
        }
    
        public virtual ObjectResult<verinner_Result> verinner()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verinner_Result>("verinner");
        }
    
        public virtual ObjectResult<verlist_Result> verlist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verlist_Result>("verlist");
        }
    
        public virtual ObjectResult<versırala_Result> versırala()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<versırala_Result>("versırala");
        }
    
        public virtual int verupdate(Nullable<int> vergiId, string vergiAdi, string vergiTipi, Nullable<decimal> tutar, Nullable<decimal> faiz, Nullable<int> kisiNo, Nullable<int> bakanlikId)
        {
            var vergiIdParameter = vergiId.HasValue ?
                new ObjectParameter("VergiId", vergiId) :
                new ObjectParameter("VergiId", typeof(int));
    
            var vergiAdiParameter = vergiAdi != null ?
                new ObjectParameter("VergiAdi", vergiAdi) :
                new ObjectParameter("VergiAdi", typeof(string));
    
            var vergiTipiParameter = vergiTipi != null ?
                new ObjectParameter("VergiTipi", vergiTipi) :
                new ObjectParameter("VergiTipi", typeof(string));
    
            var tutarParameter = tutar.HasValue ?
                new ObjectParameter("Tutar", tutar) :
                new ObjectParameter("Tutar", typeof(decimal));
    
            var faizParameter = faiz.HasValue ?
                new ObjectParameter("Faiz", faiz) :
                new ObjectParameter("Faiz", typeof(decimal));
    
            var kisiNoParameter = kisiNo.HasValue ?
                new ObjectParameter("KisiNo", kisiNo) :
                new ObjectParameter("KisiNo", typeof(int));
    
            var bakanlikIdParameter = bakanlikId.HasValue ?
                new ObjectParameter("BakanlikId", bakanlikId) :
                new ObjectParameter("BakanlikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("verupdate", vergiIdParameter, vergiAdiParameter, vergiTipiParameter, tutarParameter, faizParameter, kisiNoParameter, bakanlikIdParameter);
        }
    
        public virtual ObjectResult<telonew_Result> telonew()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<telonew_Result>("telonew");
        }
    
        public virtual ObjectResult<seyit_Result> seyit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seyit_Result>("seyit");
        }
    
        public virtual ObjectResult<MerkezeGore_Result> MerkezeGore()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MerkezeGore_Result>("MerkezeGore");
        }
    
        public virtual ObjectResult<adresegore_Result> adresegore()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<adresegore_Result>("adresegore");
        }
    
        public virtual ObjectResult<Nullable<decimal>> ankortalama()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("ankortalama");
        }
    
        public virtual ObjectResult<bknmrkzortalama_Result> bknmrkzortalama()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bknmrkzortalama_Result>("bknmrkzortalama");
        }
    }
}
