//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20._08._2023entitydbfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vergiler
    {
        public int VergiId { get; set; }
        public string VergiAdi { get; set; }
        public string VergiTipi { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<decimal> Faiz { get; set; }
        public Nullable<int> KisiNo { get; set; }
        public Nullable<int> BakanlikId { get; set; }
    }
}
